# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sharon t lin
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer and writer from New York City.
repository: https://github.com/wemake-services/jekyll-theme-hackcss
baseurl: ""  # the subpath of your site, e.g. /blog
url: http://sharontlin.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: sharon t lin 
email: sharonl@mit.edu

navigation:
  - text: blog
    url: /blog
  - text: projects
    url: /projects
  - text: writing
    url: /writing
  - text: photos
    url: /photos

